// Public API of @detaly/db: Drizzle schema (postgres-js driver, casing 'snake_case'),
// migrations in ../drizzle (generated by drizzle-kit), idempotent seeds.
export {
  createDb,
  migrateDb,
  MIGRATIONS_FOLDER,
  schema,
  type CreateDbOptions,
  type Database,
  type Db,
  type Schema,
  type Tx,
} from './client';
export type { Executor } from './executor';
export * from './schema';
export { isNoopSeed, seed, type SeedOptions, type SeedReport } from './seed';
export { EXCLUDED_SEED } from './seed/excluded';
export {
  DEFAULT_LEGAL_DIR,
  LEGAL_PLACEHOLDERS,
  LEGAL_VERSION_ENV,
  LegalSeedError,
  parseLegalFile,
  readLegalSources,
  renderLegal,
  sha256Hex,
  type LegalSeedResult,
  type LegalSource,
  type RenderedLegal,
} from './seed/legal';
