// Public API of @detaly/db: Drizzle schema (postgres-js driver, casing 'snake_case'),
// migrations in ../drizzle (generated by drizzle-kit), idempotent seeds.
export {
  createDb,
  migrateDb,
  MIGRATIONS_FOLDER,
  schema,
  type CreateDbOptions,
  type Database,
  type Db,
  type Schema,
  type Tx,
} from './client';
export type { Executor } from './executor';
// One consistent snapshot (REPEATABLE READ, READ ONLY) for read models of several queries
export { READ_SNAPSHOT, readSnapshot } from './snapshot';
// Query operators re-exported so apps (web) use this package's single drizzle-orm instance
// instead of depending on drizzle-orm themselves (a second copy without the postgres peer).
export {
  and,
  asc,
  desc,
  eq,
  gt,
  gte,
  inArray,
  isNotNull,
  isNull,
  lt,
  lte,
  ne,
  or,
  sql,
  type SQL,
} from 'drizzle-orm';
export * from './schema';
export { isNoopSeed, seed, type SeedOptions, type SeedReport } from './seed';
export { EXCLUDED_SEED } from './seed/excluded';
export {
  DEFAULT_LEGAL_DIR,
  LEGAL_PLACEHOLDERS,
  LEGAL_VERSION_ENV,
  LegalSeedError,
  parseLegalFile,
  readLegalSources,
  renderLegal,
  sha256Hex,
  type LegalSeedResult,
  type LegalSource,
  type RenderedLegal,
} from './seed/legal';
