#!/usr/bin/env node
// Bundles content/legal into apps/web/src/server/demo/legal-bundle.ts for DEMO_MODE, where
// there is no database for the seed to sync the texts into (docs/design.md, section 5). The
// sources are stored with placeholders; server/demo/documents.ts renders them with renderLegal
// and the env requisites at request time, exactly as the seed would.
//
//   pnpm --filter @detaly/web gen:legal          # rewrite the bundle
//   pnpm --filter @detaly/web gen:legal --check  # exit 1 when it is out of date
//
// test/demo-legal-bundle.test.ts fails while the committed bundle differs from content/legal.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_LEGAL_DIR, readLegalSources, type LegalSource } from '@detaly/db';
import { format, resolveConfig } from 'prettier';

const webDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const BUNDLE_PATH = path.join(webDir, 'src', 'server', 'demo', 'legal-bundle.ts');

/** The module text for these sources (formatted with the repository's prettier config). */
export async function renderBundle(sources: readonly LegalSource[]): Promise<string> {
  const entries = sources.map((source) => ({
    kind: source.kind,
    version: source.version,
    title: source.title,
    sourcePath: source.sourcePath,
    body: source.body,
  }));
  const text = [
    '// Generated by apps/web/scripts/gen-legal-bundle.ts from content/legal: do not edit by hand.',
    '// Regenerate with `pnpm --filter @detaly/web gen:legal` (test/demo-legal-bundle.test.ts).',
    "import type { LegalSource } from '@detaly/db';",
    '',
    `export const LEGAL_BUNDLE: readonly LegalSource[] = ${JSON.stringify(entries, null, 2)};`,
    '',
  ].join('\n');
  const config = (await resolveConfig(BUNDLE_PATH)) ?? {};
  return format(text, { ...config, filepath: BUNDLE_PATH });
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const next = await renderBundle(await readLegalSources(DEFAULT_LEGAL_DIR));
  const current = await readFile(BUNDLE_PATH, 'utf8').catch(() => '');
  if (check) {
    if (current !== next) {
      console.error('[gen-legal-bundle] legal-bundle.ts is out of date: run gen:legal');
      process.exit(1);
    }
    console.log('[gen-legal-bundle] up to date');
    return;
  }
  if (current === next) {
    console.log('[gen-legal-bundle] unchanged');
    return;
  }
  await writeFile(BUNDLE_PATH, next);
  console.log(`[gen-legal-bundle] wrote ${path.relative(webDir, BUNDLE_PATH)}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
