/**
 * Legal documents of the demo (DEMO_MODE): content/legal bundled into the build
 * (legal-bundle.ts, generated by scripts/gen-legal-bundle.ts) and rendered with renderLegal and
 * the env requisites, the same way the seed renders them into document_versions.
 *
 * The version is chosen like getPublishedDocument does: LEGAL_<KIND>_VERSION when it is set and
 * every placeholder of it has a value (published), otherwise the latest version as a draft.
 */
import { createHash } from 'node:crypto';
import type { Env } from '@detaly/config';
import { LEGAL_VERSION_ENV, renderLegal, type LegalSource } from '@detaly/db';
import type { DocumentKind } from '@detaly/domain';
import type { LegalDocument } from '../documents';
import { LEGAL_BUNDLE } from './legal-bundle';

/** Stable uuid-shaped id of a bundled version (no database row exists). */
function demoDocumentId(source: Pick<LegalSource, 'kind' | 'version'>): string {
  const hex = createHash('sha256').update(`demo:${source.kind}:${source.version}`).digest('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

function toDocument(source: LegalSource, env: Env, publish: boolean): LegalDocument | null {
  const { rendered, problems } = renderLegal(source, env, publish ? 'publish' : 'draft');
  if (problems.length > 0) return null;
  return {
    id: demoDocumentId(source),
    kind: source.kind,
    version: source.version,
    title: rendered.title,
    bodyMd: rendered.bodyMd,
    sha256: rendered.sha256,
    publishedAt: null,
    isDraft: !publish,
  };
}

export function demoDocument(
  kind: DocumentKind,
  env: Env,
  bundle: readonly LegalSource[] = LEGAL_BUNDLE,
): LegalDocument | null {
  const versions = bundle
    .filter((source) => source.kind === kind)
    .sort((a, b) => a.version.localeCompare(b.version));
  const wanted = env[LEGAL_VERSION_ENV[kind]];
  const selected = wanted ? versions.find((source) => source.version === wanted) : undefined;
  if (selected) {
    const published = toDocument(selected, env, true);
    if (published) return published;
  }
  const latest = versions.at(-1);
  return latest ? toDocument(latest, env, false) : null;
}
